# One Hot Encoding Algorithm

<img src="image/onehotencoding.png",width=500,height=500>

In [1]:
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [5]:
docs = ['Merhaba arkadaşlar nasılsınız arkadaşlar',
        'Arkadaşlar Deepcon18 atölye çalışmasına hoşgeldiniz',
        'Bugun sizlerle birlikte arkadaşlar embedding yöntemlerini öğreneceğiz',
        'Artık şimdi yeni yöntemlere göz atalım']

In [6]:
dict_list = []
for i in docs:
    value = i.split()
    for j in value:
        dict_list.append(j)

In [7]:
print(dict_list)
print(len(dict_list))

['Merhaba', 'arkadaşlar', 'nasılsınız', 'arkadaşlar', 'Arkadaşlar', 'Deepcon18', 'atölye', 'çalışmasına', 'hoşgeldiniz', 'Bugun', 'sizlerle', 'birlikte', 'arkadaşlar', 'embedding', 'yöntemlerini', 'öğreneceğiz', 'Artık', 'şimdi', 'yeni', 'yöntemlere', 'göz', 'atalım']
22


In [8]:
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(dict_list)
print(integer_encoded)
print(len(integer_encoded))

[ 4  5 12  5  0  3  7 17 11  2 13  8  5  9 16 18  1 19 14 15 10  6]
22


In [9]:
OneHotEncoder()

OneHotEncoder(categorical_features='all', dtype=<class 'numpy.float64'>,
       handle_unknown='error', n_values='auto', sparse=True)

In [10]:
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
print(integer_encoded)
print(integer_encoded.size)

[[ 4]
 [ 5]
 [12]
 [ 5]
 [ 0]
 [ 3]
 [ 7]
 [17]
 [11]
 [ 2]
 [13]
 [ 8]
 [ 5]
 [ 9]
 [16]
 [18]
 [ 1]
 [19]
 [14]
 [15]
 [10]
 [ 6]]
22


In [11]:
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [13]:
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
print(inverted)

['Merhaba']


/home/halil/anaconda/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


reference : https://machinelearningmastery.com/how-to-one-hot-encode-sequence-data-in-python/